// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package injector

import (
	"ether_todo/pkg/todo"
	"ether_todo/pkg/todo/controller/persistence"
)

// Injectors from wire.go:

func TodoUsecase() todo.IUsecase {
	iRepository := persistence.NewTodoListRepo()
	iService := todo.NewService(iRepository)
	iUsecase := todo.NewUsecase(iRepository, iService)
	return iUsecase
}
