// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package injector

import (
	"ether_todo/pkg/adapter/persistence"
	"ether_todo/pkg/todo"
)

// Injectors from wire.go:

func TodoService() todo.IService {
	iRepository := persistence.NewTodoListRepo()
	iService := todo.NewService(iRepository)
	return iService
}
