// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package glue

import (
	"github.com/jinzhu/gorm"
	"github.com/labstack/echo/v4"
)

// Injectors from wire.go:

func DefaultHttpServer() *echo.Echo {
	server := ProvideServiceCfg()
	echoEcho := DefaultEchoHttpServer(server)
	return echoEcho
}

func DefaultGorm() (*gorm.DB, error) {
	database := ProvideDBsCfg()
	db, err := DefaultGormDB(database)
	if err != nil {
		return nil, err
	}
	return db, nil
}

// wire.go:

//Providers
func ProvideServiceCfg() Server {
	i := ReadConfig(Server{})
	cfg := i.(Server)
	return cfg
}

func ProvideDBsCfg() Database {
	i := ReadConfig(Database{})
	cfg := i.(Database)
	return cfg
}

func ProvideLogCfg() Log {
	i := ReadConfig(Log{})
	cfg := i.(Log)
	return cfg
}