database:
  dialect: postgres
  address: infrastructure.server.ngotzmann.net
  port: 5432
  database: ether_todo
  user: ether_todo
  password: YhoGmhht0CsR3b1VY1ma2vV5NYxlrByL7jL
  maxIdleConnections: 10
  logging: true
  audit: false
