// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package modules

import (
	"github.com/jinzhu/gorm"
	"github.com/labstack/echo/v4"
)

// Injectors from wire.go:

func DefaultHttpServer() *echo.Echo {
	config := DefaultConfig()
	echoEcho := DefaultEchoHttpServer(config)
	return echoEcho
}

func DefaultGorm() (*gorm.DB, error) {
	config := DefaultConfig()
	logger := DefaultFileLogger(config)
	db, err := DefaultGormDB(config, logger)
	if err != nil {
		return nil, err
	}
	return db, nil
}
