server:
  # local, dev, staging, production
  environment: local
  address: 127.0.0.1
  port: 3000

webservice:
  sessionSecret: "VmkOCdTRkjzkxWuLFN8JI0jDP0g2N4LiS7h"
  sessionName: "ether_todo"

database:
  dialect:
  address:
  port:
  database:
  user:
  password:
  maxIdleConnections:
  logging: false

#panic, fatal, error, warn, info, debug, trace
logging:
  file: ../service.log
  level: info
  timestampFormat: "02-01-2006_15:04:05"